/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ASpace: typeof import('ant-design-vue/es')['Space']
    Footer: typeof import('./src/components/shared/Footer.vue')['default']
    FormSearch: typeof import('./src/components/Home/FormSearch.vue')['default']
    Header: typeof import('./src/components/shared/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/shared/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableList: typeof import('./src/components/Home/TableList.vue')['default']
    Title: typeof import('./src/components/shared/Title.vue')['default']
  }
}
